name: "Input Validation"
description: "Input Validation for the parameters passed"
inputs:
  source_env:
    description: source environment
    required: true
  target_env:
    description: Target environment
    required: true
  platform:
    description: Target Platform
    required: true
  component:
    description: Deployed Component
    required: true
  tag:
    description: Deployed tag
    required: true
  app_version:
    description: App version
    required: true
runs:
  using: composite
  steps:
    - name: Validate Inputs
      run: |
        valid_src_env=(dev spro int stage preprod)
        valid_target_env=(int stage preprod prod)
        valid_components=("integration-server: 10.5.22.04" "integration-server: 10.7.22.04" "integration-server: 10.11.22.04" "universal-messaging: 10.5.22.04" "universal-messaging: 10.7.22.04" "universal-messaging: 10.11.22.04" "terracotta-server: 10.5.22.04" "terracotta-server: 10.7.22.04" "terracotta-server: 10.11.22.04" )
        valid_platform=(aws azure all)
        if [[ ! (" ${valid_src_env[*]} " =~ " ${{inputs.source_env}} ") ]]
        then
          echo "Provide the proper environment listed here [ ${valid_src_env[*]} ] for source env" 
          exit 1
        fi
        
        if [[ ! (" ${valid_target_env[*]} " =~ " ${{inputs.target_env}} ") ]]
        then
          echo "Provide the proper environment listed here [ ${valid_target_env[*]} ] for target env" 
          exit 1
        fi
        
        if [[ ! (" ${valid_platform[*]} " =~ " ${{inputs.platform}} ") ]]
        then
          echo "Provide the proper platforms listed here [ ${valid_platform[*]} ]" 
          exit 1
        fi
        IFS="," read -a components <<< ${{ inputs.component }}
        IFS="," read -a tags <<< ${{ inputs.tag }}
        if [[ ${#components[@]} -ne ${#tags[@]} ]]
        then
          echo "Image and tags count are mismatching , Pls provide crt image and tag pair"
          exit 1
        fi
        for cldp_component in ${!components[@]}
        do
          if [[ ! (" ${valid_components[*]} " =~ " ${components[$cldp_component]}: ${tags[$cldp_component]} ") ]]
          then
            echo " ${components[$cldp_component]}: ${tags[$cldp_component]} not found"
            exit 1 
          fi 
        done
      shell: bash
