name: "Input Validation"
description: "Input Validation for the parameters passed"
inputs:
  target_env:
    description: Target environment
    required: true
  platform:
    description: Target Platform
    required: true
  component:
    description: Deployed Component
    required: true
  tag:
    description: Deployed tag
    required: true
  app_version:
    description: App version
    required: true
runs:
  using: composite
  steps:
    - name: Validate Inputs
      run: |
        valid_env=(dev spro int stage)
        valid_components=(integration-server universal-messaging)
        valid_platform=(aws azure all)
        if [[ ! (" ${valid_env[*]} " =~ " ${{inputs.target_env}} ") ]]
        then
          echo "Provide the proper environment listed here [ ${valid_env[*]} ]" 
          exit 1
        fi
        if [[ ! (" ${valid_platform[*]} " =~ " ${{inputs.platform}} ") ]]
        then
          echo "Provide the proper platforms listed here [ ${valid_platform[*]} ]" 
          exit 1
        fi
        IFS="," read -a components <<< ${{ inputs.component }}
        for cldp_component in ${!components[@]}
        do
          if [[ ! (" ${valid_components[*]} " =~ " ${components[$cldp_component]} ") ]]
          then
            echo "Invalid Components ${components[$cldp_component]}"
            exit 1 
          else
             echo "$cldp_component"
          fi 
        done
        for cldp_component in ${components[@]}
        do
         echo "$cldp_component"
        done
        IFS="," read -a tags <<< ${{ inputs.tag }}
          if [[ ${#components[@]} -ne ${#tags[@]} ]]
          then
            echo "Invalid Tags and Image pairs"
            echo ${components[@]}
            echo ${tags[@]}
            exit 1
          fi
      shell: bash
