name: learn-github-actions
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'sarath'
      home:
        description: 'location'
        required: false
        default: 'Gobi'
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
  call_another:
      runs-on: self-hosted
      steps:
       - uses: actions/checkout@v2
         with:
          path: new/actions
       -  name: Call s3 cration file
          if: github.event.inputs.name == 'sarath'
          uses: /new/actions@main
          with: 
            name: ${{ github.event.inputs.name }}
            location: ${{ github.event.inputs.home }}
