name: CLDP Promotion Job
on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform (aws,azure,all)"
        default: aws
        required: true
      source_env:
        description: "Source Environment(dev spro int stage preprod)"
        default: dev
        required: true
      target_env:
        description: "Target Environment(int stage preprod prod)"
        default: int
        required: true
      components:
        description: "Components to promote ( all integration-server  universal-messaging terracotta-server)"
        default: terracotta-server
        required: true
      tags:
        description: "Tags of corresponding components ( all 10.5.22.04 10.7.22.04 10.11.22.04 10.12.22.04)"
        required: false
      app_version:
        description: "Current App Version"
        default: "1012"
        required: true
jobs:
  Promote-Images:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
         name: Checkout the current repository

       - name: Apply Env File
         id: vars
         run: |
          echo "${{ secrets.AWS_DEV_ACCESS_KEY }}"
          chmod 777 variable.env
          ./variable.env

       - name: Validate Inputs
         uses: ./image-deployment/actions/promotion-inputvalidation
         with:
            target_env: ${{ github.event.inputs.target_env }}
            source_env: ${{ github.event.inputs.source_env }}
            component: ${{ github.event.inputs.components }}
            tag: ${{ github.event.inputs.tags }}
            platform: ${{ github.event.inputs.platform }}
            app_version: ${{ github.event.inputs.currentversion }}
            validversion: ${{ steps.vars.outputs.CURRENT_MAJOR_VERSION }}
            
       - name: Configure AWS Credentials for dev ecr
         uses: aws-actions/configure-aws-credentials@v1
         with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEV_REGION }}
         if: github.event.inputs.platform == 'dev' && github.event.inputs.platform == 'aws'
       -  name: ECR RnD Login
          id: ecr-dev-login
          uses: aws-actions/amazon-ecr-login@v1
          if: github.event.inputs.platform == 'dev' && github.event.inputs.platform == 'aws'
          
       - name: AWS Int login
         uses: aws-actions/configure-aws-credentials@v1
         with:
            aws-access-key-id: ${{ secrets.AWS_INT_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_INT_SECRET_KEY }}
            aws-region: ${{ secrets.AWS_INT_REGION }}
         if: github.event.inputs.target_env == 'int' && (github.event.inputs.platform == 'aws') 
       - name: ECR Int Login
         id: ecr-int-login
         uses: aws-actions/amazon-ecr-login@v1
         if: github.event.inputs.target_env == 'int' && (github.event.inputs.platform == 'aws')

       - name: Configure AWS Credentials for s3
         uses: aws-actions/configure-aws-credentials@v1
         with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETKEY }}
          aws-region: ${{ secrets.AWS_REGION }}

 
       - name: Set up Reg URLs
         id: img-regs
         run: |
          echo "::set-output name=AWS_SOURCE_REPO_PREFIX::${{ steps.vars.outputs.AWS_REPO_PREFIX }}"
          echo "::set-output name=AWS_SOURCE_REG_URL::${{ steps.ecr-dev-login.outputs.registry }}"
          echo 
          if [[ ${{ github.event.inputs.target_env }} == "int" ]]
          then
            echo "::set-output name=AWS_TARGET_REG_URL::${{ steps.ecr-int-login.outputs.registry }}"
          else
            echo "::set-output name=AWS_TARGET_REG_URL::${{ steps.ecr-dev-login.outputs.registry }}"
          fi


            
       - name: Promote Images to Env
         uses: ./image-deployment/actions/promote-image
         with:
          platform: ${{ github.event.inputs.platform }}
          source_env: ${{ github.event.inputs.source_env }}
          target_env: ${{ github.event.inputs.target_env }}
          components: ${{ github.event.inputs.components }}
          tags: ${{ github.event.inputs.tags }}
          app_version: ${{ github.event.inputs.app_version }}
          bucket_name: cldp
          metadata_path: buildfiles
          source_aws_registry: ${{ steps.img-regs.outputs.AWS_SOURCE_REG_URL }}
          target_aws_registry: ${{ steps.img-regs.outputs.AWS_TARGET_REG_URL }}
          source_aws_repo_prefix: ${{ steps.img-regs.outputs.AWS_SOURCE_REPO_PREFIX }}
        

